name: flutter_design_app
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  http: ^1.1.2
  shared_preferences: ^2.2.2
  cross_file: ^0.3.3+8
  cached_network_image: ^3.3.0
  google_maps_flutter: ^2.5.0
  google_maps_flutter_platform_interface: ^2.4.1
  carousel_slider: ^4.2.1
  intl: ^0.19.0
  provider: ^6.1.1
  mockito: ^5.4.4
  country_pickers: ^2.0.0
  pin_code_fields: ^8.0.1
  image_picker: ^1.0.7
  permission_handler: ^11.3.1
  device_information: ^0.0.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/image/



  fonts:
    - family: Roboto
      fonts:
        - asset: assets/font/Roboto-Regular.ttf
          weight: 400
        - asset: assets/font/Roboto-Medium.ttf
          weight: 500
        - asset: assets/font/Roboto-Bold.ttf
          weight: 700
        - asset: assets/font/Roboto-Black.ttf
          weight: 900




